### ISSUE TITLE
请求提供数据库的相关脚本

### ISSUE THREAD

**Issue by HailySo** [MichaelWang2000/Iris_Recognition#2]
由于没有相关的数据库model模型文件，想求助作者提供一下数据库的脚本，感激不尽！

**Comment by HailySo** [comment]
如果可以的话，还想要一些带数据的相关数据库脚本

**Comment by MichaelWang2000** [comment]
不好意思，本系统没有训练模型，主要是通过算法对图片进行处理，然后对最终的图片与数据库存储进行对比进行识别的

**Comment by HailySo** [comment]
> 不好意思，本系统没有训练模型，主要是通过算法对图片进行处理，然后对最终的图片与数据库存储进行对比进行识别的

抱歉我的表述可能不是太准确，是因为这个管理系统的数据库部分没有提供相应的建表等SQL脚本，所以想请求一下作者能不能导出数据库IrisRecognition的所有表结构和表数据，因为如果没有这些的话我只能从Qt的一些文件的一些"select * from"语句的代码推测数据库的结构，很容易出问题

所以请求作者能够从已经建立好的数据库IrisRecognition中导出相应的建表SQL文件，感激不尽

**Comment by MichaelWang2000** [comment]
我更新在repo里了

**Comment by HailySo** [comment]
非常感谢~！
